### ISSUE TITLE
No way to choose what abilities the player has in rayman origins

### ISSUE THREAD

**Issue by Arcadius2006** [RayCarrot/RaymanControlPanel#12]
when launching the game in debug mode from a specific map, the player only has the abilities from when the game is only started (walk, jump, run). an ability to give rayman his full moveset, or even only specific abilities would be great

**Comment by RayCarrot** [comment]
Sadly there is no debug command for changing your abilities in the game, so with the way this is set up that won't be possible. I have been looking a bit at restoring the game's debug menu (which has a lot more options and also allows changing maps), but sadly there are some issues with it not rendering correctly. So for now there's no good solution to this I can provide.
